# Generated by Django 4.0.1 on 2024-02-04 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0003_alter_image_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="images",
            new_name="image",
        ),
    ]
