# Generated by Django 4.0.1 on 2024-02-14 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_rename_images_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='title',
            new_name='place',
        ),
    ]
